services:
#    paddlere.example:
#        class: PaddlereBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    paddlere.manager.device:
        class: PaddlereBundle\Entity\DeviceManager
        arguments: ["@doctrine"]

    paddlere.manager.tag:
        class: PaddlereBundle\Entity\TagManager
        arguments: ["@doctrine"]

    paddlere.manager.field:
        class: PaddlereBundle\Entity\FieldManager
        arguments: ["@doctrine"]

    paddlere.manager.event:
        class: PaddlereBundle\Entity\EventManager
        arguments: ["@doctrine"]

    paddlere.admin.facility:
        class: PaddlereBundle\Admin\FacilityAdmin
        arguments: [~, PaddlereBundle\Entity\Facility, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setup, label: Facility }

    paddlere.admin.field:
        class: PaddlereBundle\Admin\FieldAdmin
        arguments: [~, PaddlereBundle\Entity\Field, PaddlereBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setup, label: Field }
        calls:
            - [ setTemplate, [timeline, PaddlereBundle:FieldAdmin:timeline.html.twig]]

    paddlere.admin.device:
        class: PaddlereBundle\Admin\DeviceAdmin
        arguments: [~, PaddlereBundle\Entity\Device, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setup, label: Device }

    paddlere.admin.device_field:
        class: PaddlereBundle\Admin\DeviceFieldAdmin
        arguments: [~, PaddlereBundle\Entity\DeviceField, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setup, label: DeviceField }

    paddlere.admin.guest:
        class: PaddlereBundle\Admin\GuestAdmin
        arguments: [~, PaddlereBundle\Entity\Guest, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setup, label: Guest }

    paddlere.admin.tag:
        class: PaddlereBundle\Admin\TagAdmin
        arguments: [~, PaddlereBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setup, label: Tag }

    paddlere.admin.event:
        class: PaddlereBundle\Admin\EventAdmin
        arguments: [~, PaddlereBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Manage, label: Event }

    paddlere.service.event:
        class: PaddlereBundle\Service\EventService
        arguments: ["@logger", "@paddlere.manager.event", "@paddlere.manager.device", "@paddlere.manager.field" ]

